import type {
    RecentActivity,
    RecentOrder,
    LowStockProduct,
    PurchaseSummary,
    CustomerSummary,
    EmployeeSummary,
    OrderSummary,
    StockSummary,
} from "./dashboard.types"

export const stockSummary: StockSummary = {
    totalProducts: 1250,
    totalVariants: 3840,
    totalStockQuantity: 45820,
    totalStockValue: "8450000",
    lowStockCount: 42,
    outOfStockCount: 17,
}

export const orderSummary: OrderSummary = {
    totalOrders: 1248,
    pendingOrders: 42,
    processingOrders: 35,
    shippedOrders: 18,
    deliveredOrders: 1120,
    cancelledOrders: 33,
}

export const employeeSummary: EmployeeSummary = {
    totalEmployees: 45,
    activeEmployees: 42,
    newEmployees: 3,
}

export const customerSummary: CustomerSummary = {
    totalCustomers: 5420,
    newCustomers: 125,
    activeCustomers: 850,
    returningCustomers: 420,
    customerGrowth: 8.7,
}

export const purchaseSummary: PurchaseSummary = {
    totalPurchases: "850000",
    todayPurchases: "25000",
    totalPurchaseOrders: 325,
    pendingPurchases: 12,
    purchaseGrowth: 8.4,
}

export const recentOrders: RecentOrder[] = [
    {
        id: "order_001",
        orderNumber: "ORD-2026-1001",
        customer: {
            id: "customer_001",
            name: "John Doe",
            image: "https://i.pravatar.cc/150?img=12",
        },
        total: "1250.00",
        status: "PROCESSING",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T16:46:18.394Z",
    },
    {
        id: "order_002",
        orderNumber: "ORD-2026-1002",
        customer: {
            id: "customer_002",
            name: "Sarah Wilson",
            image: "https://i.pravatar.cc/150?img=32",
        },
        total: "845.50",
        status: "SHIPPED",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T15:32:10.120Z",
    },
    {
        id: "order_003",
        orderNumber: "ORD-2026-1003",
        customer: {
            id: "customer_003",
            name: "Robert Smith",
            image: "https://i.pravatar.cc/150?img=11",
        },
        total: "2390.00",
        status: "DELIVERED",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "order_004",
        orderNumber: "ORD-2026-1004",
        customer: {
            id: "customer_004",
            name: "Michael Brown",
            image: "https://i.pravatar.cc/150?img=15",
        },
        total: "560.75",
        status: "PENDING",
        paymentStatus: "PENDING",
        createdAt: "2026-09-21T13:45:22.300Z",
    },
    {
        id: "order_005",
        orderNumber: "ORD-2026-1005",
        customer: {
            id: "customer_005",
            name: "Emily Davis",
            image: "https://i.pravatar.cc/150?img=47",
        },
        total: "1799.99",
        status: "PROCESSING",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T12:25:15.800Z",
    },
    {
        id: "order_006",
        orderNumber: "ORD-2026-1006",
        customer: {
            id: "customer_006",
            name: "Daniel Miller",
            image: null,
        },
        total: "320.00",
        status: "CANCELLED",
        paymentStatus: "REFUNDED",
        createdAt: "2026-09-21T11:10:08.200Z",
    },
    {
        id: "order_007",
        orderNumber: "ORD-2026-1007",
        customer: {
            id: "customer_007",
            name: "Olivia Johnson",
            image: "https://i.pravatar.cc/150?img=22",
        },
        total: "450.00",
        status: "SHIPPED",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T10:05:55.600Z",
    },
    {
        id: "order_008",
        orderNumber: "ORD-2026-1008",
        customer: {
            id: "customer_008",
            name: "William Lee",
            image: "https://i.pravatar.cc/150?img=29",
        },
        total: "980.00",
        status: "DELIVERED",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T09:50:42.100Z",
    },
    {
        id: "order_009",
        orderNumber: "ORD-2026-1009",
        customer: {
            id: "customer_009",
            name: "Sophia Martinez",
            image: null,
        },
        total: "150.00",
        status: "PENDING",
        paymentStatus: "PENDING",
        createdAt: "2026-09-21T08:35:30.400Z",
    },
    {
        id: "order_010",
        orderNumber: "ORD-2026-1010",
        customer: {
            id: "customer_010",
            name: "James Anderson",
            image: "https://i.pravatar.cc/150?img=18",
        },
        total: "2200.00",
        status: "PROCESSING",
        paymentStatus: "PAID",
        createdAt: "2026-09-21T07:20:18.900Z",
    },
    {
        id: "order_011",
        orderNumber: "ORD-2026-1011",
        customer: {
            id: "customer_011",
            name: "Ava Thomas",
            image: "https://i.pravatar.cc/150?img=25",
        },
        total: "675.00",
        status: "CANCELLED",
        paymentStatus: "REFUNDED",
        createdAt: "2026-09-21T06:15:05.300Z",
    }
]

export const lowStockProducts: LowStockProduct[] = [
    {
        variantId: "variant_001",
        sku: "IPH15-BLK-128",
        productId: "product_001",
        productName: "iPhone 15",
        productImage: "https://images.unsplash.com/photo-1592899677977-9c10ca588bbd",
        quantity: 3,
    },
    {
        variantId: "variant_002",
        sku: "SAM-S24-BLK-256",
        productId: "product_002",
        productName: "Samsung Galaxy S24",
        productImage: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c",
        quantity: 5,
    },
    {
        variantId: "variant_003",
        sku: "MAC-AIR-M2-256",
        productId: "product_003",
        productName: "MacBook Air M2",
        productImage: "https://images.unsplash.com/photo-1517336714739-489689fd1ca8",
        quantity: 2,
    },
    {
        variantId: "variant_004",
        sku: "SONY-WH1000XM5",
        productId: "product_004",
        productName: "Sony WH-1000XM5",
        productImage: "https://images.unsplash.com/photo-1546435770-a3e426bf472b",
        quantity: 4,
    },
    {
        variantId: "variant_005",
        sku: "LOG-MX-MASTER3",
        productId: "product_005",
        productName: "Logitech MX Master 3S",
        productImage: null,
        quantity: 6,
    },
    {
        variantId: "variant_006",
        sku: "AIRPODS-PRO-2",
        productId: "product_006",
        productName: "AirPods Pro 2",
        productImage: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434",
        quantity: 1,
    }, {
        variantId: "variant_007",
        sku: "NINT-NSWITCH-2026",
        productId: "product_007",
        productName: "Nintendo Switch OLED",
        productImage: "https://images.unsplash.com/photo-1611078480730-1c3e5f8b9f4e",
        quantity: 2,
    }, {
        variantId: "variant_008",
        sku: "DELL-XPS-13-2026",
        productId: "product_008",
        productName: "Dell XPS 13 2026",
        productImage: "https://images.unsplash.com/photo-1587825140708-1c3e5f8b9f4e",
        quantity: 3,
    }, {
        variantId: "variant_009",
        sku: "HP-SPECTRE-X360",
        productId: "product_009",
        productName: "HP Spectre x360",
        productImage: null,
        quantity: 5,
    }, {
        variantId: "variant_010",
        sku: "GOOG-PIXEL-7-PRO",
        productId: "product_010",
        productName: "Google Pixel 7 Pro",
        productImage: "https://images.unsplash.com/photo-1611078480730-1c3e5f8b9f4e",
        quantity: 2,
    }
]

export const recentActivities: RecentActivity[] = [
    {
        id: "activity_001",
        type: "CREATE",
        module: "Products",
        action: "Product Created",
        description: "Created a new product iPhone 15 Pro",
        entityType: "Product",
        entityId: "product_001",
        userId: "user_001",
        user: {
            id: "user_001",
            name: "John Doe",
            email: "john@example.com",
            avatar: "https://i.pravatar.cc/150?img=12",
        },
        createdAt: "2026-09-21T16:46:18.394Z",
    },

    {
        id: "activity_002",
        type: "UPDATE",
        module: "Orders",
        action: "Order Updated",
        description: "Updated order #ORD-10245 status to Processing",
        entityType: "Order",
        entityId: "order_001",
        userId: "user_002",
        user: {
            id: "user_002",
            name: "Sarah Wilson",
            email: "sarah@example.com",
            avatar: "https://i.pravatar.cc/150?img=32",
        },
        createdAt: "2026-09-21T15:32:10.120Z",
    },

    {
        id: "activity_003",
        type: "CREATE",
        module: "Customers",
        action: "Customer Created",
        description: "Added a new customer Robert Smith",
        entityType: "Customer",
        entityId: "customer_001",
        userId: "user_003",
        user: {
            id: "user_003",
            name: "Robert Smith",
            email: "robert@example.com",
            avatar: "https://i.pravatar.cc/150?img=11",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "activity_004",
        type: "DELETE",
        module: "Products",
        action: "Product Deleted",
        description: "Deleted product Samsung Galaxy S24",
        entityType: "Product",
        entityId: "product_002",
        userId: "user_004",
        user: {
            id: "user_004",
            name: "Michael Brown",
            email: "michael@example.com",
            avatar: "https://i.pravatar.cc/150?img=13",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "activity_005",
        type: "UPDATE",
        module: "Inventory",
        action: "Stock Updated",
        description: "Updated stock quantity for product MacBook Air M2",
        entityType: "Product",
        entityId: "product_003",
        userId: "user_005",
        user: {
            id: "user_005",
            name: "Emily Davis",
            email: "emily@example.com",
            avatar: "https://i.pravatar.cc/150?img=14",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "activity_006",
        type: "CREATE",
        module: "Orders",
        action: "Order Created",
        description: "Created a new order #ORD-10246 for customer Olivia Johnson",
        entityType: "Order",
        entityId: "order_002",
        userId: "user_006",
        user: {
            id: "user_006",
            name: "Olivia Johnson",
            email: "olivia@example.com",
            avatar: "https://i.pravatar.cc/150?img=15",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "activity_007",
        type: "UPDATE",
        module: "Customers",
        action: "Customer Updated",
        description: "Updated customer Sophia Martinez's contact information",
        entityType: "Customer",
        entityId: "customer_002",
        userId: "user_007",
        user: {
            id: "user_007",
            name: "Sophia Martinez",
            email: "sophia@example.com",
            avatar: "https://i.pravatar.cc/150?img=16",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    },
    {
        id: "activity_008",
        type: "DELETE",
        module: "Orders",
        action: "Order Deleted",
        description: "Deleted order #ORD-10247 for customer Daniel Miller",
        entityType: "Order",
        entityId: "order_003",
        userId: "user_008",
        user: {
            id: "user_008",
            name: "Daniel Miller",
            email: "daniel@example.com",
            avatar: "https://i.pravatar.cc/150?img=17",
        },
        createdAt: "2026-09-21T14:18:42.500Z",
    }
]